export default function Home({hidden}) {
  return <section id="home-panel" aria-labelledby="home-title" hidden={hidden}>
    <div className="landing-intro"><p className="eyebrow">L3V AI TOOLS</p><h1 id="home-title">What will you create?</h1><p>A name. A signature. Your next video.<br />Choose a tool and start with what you have.</p></div>
    <div className="tool-tiles">
      <a className="tool-tile" href="#logo"><div className="tile-top"><span className="tile-category">IDENTITY</span><span aria-hidden="true">↗</span></div><span className="tile-sample" aria-hidden="true">Aa</span><h2>Magic Identity</h2><p>One name, three creative directions.</p><div className="tile-variations"><span>Magic Name</span><span>Magic Initials</span><span>Magic Signature</span></div><div className="tile-bottom"><span>Explore your name</span><span className="tile-number">01</span></div></a>
      <a className="tool-tile" href="#video"><div className="tile-top"><span className="tile-category">VIDEO</span><span aria-hidden="true">↗</span></div><span className="tile-sample video-sample" aria-hidden="true">▷</span><h2>AI Video Suggestion</h2><p>Share a video, screenshot, or link. We will show you how to create something similar, which AI models to use, and how much it could cost on popular platforms.</p><div className="tile-bottom"><span>Reference preview · Analysis coming soon</span><span className="tile-number">02</span></div></a>
      {[['Room for an idea.', 'The next tool starts here.'], ['Something to come.', 'A little space for the next idea.']].map(([title, copy], i) => <article key={title} className="tool-tile empty-tool" aria-label="Future tool, coming soon"><div className="tile-top"><span className="tile-category">UP NEXT</span></div><span className="tile-sample" aria-hidden="true">+</span><h2>{title}</h2><p>{copy}</p><div className="tile-bottom"><span>Coming soon</span><span className="tile-number">0{i + 3}</span></div></article>)}
    </div><p className="landing-note">A growing collection. AI generation is being connected; available previews are ready to explore.</p>
  </section>;
}
