import {useEffect,useRef,useState} from 'react';
import {accessToken,saveAccessToken,clearAccessToken,tokenFromImage,receiptImage,savedCertificateImage,saveCertificateImage} from '../lib/master-access.mjs';
async function validate(credential){const response=await fetch('/api/invitation/validate',{headers:{'X-L3V-Invitation':credential}});if(!response.ok)throw Error('This invitation is not valid.');return response.json()}
export default function InvitationGate({children}){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState('Checking invitation…'),[phrase,setPhrase]=useState(''),[tokenImage,setTokenImage]=useState('');
  const tokenDialog=useRef(null);
  async function enter(credential){setBusy(true);try{const result=await validate(credential);saveAccessToken(credential,result.accountId);setReady(true);setMessage('');return true}catch(e){clearAccessToken();setReady(false);setMessage(e.message);return false}finally{setBusy(false)}}
  useEffect(()=>{const credential=accessToken();if(credential)enter(credential);else{setBusy(false);setMessage('Upload your certificate or enter its three-word secret.')}},[]);
  async function upload(file){if(!file)return;setMessage('Reading certificate…');try{const credential=await tokenFromImage(file);if(await enter(credential))await saveCertificateImage(file)}catch(e){setBusy(false);setMessage(e.message)}}
  async function showToken(){setTokenImage(savedCertificateImage()||await receiptImage());tokenDialog.current?.showModal()}
  async function download(){const a=document.createElement('a');a.href=await receiptImage();a.download='l3v-private-access-receipt.png';a.click()}
  if(!ready)return <main className="invitation-gate"><p className="eyebrow">INVITATION ONLY</p><h1>Your invitation is your key.</h1><p>Upload your private certificate or type its three-word secret.</p><label className="certificate-upload"><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>upload(e.target.files[0])}/><strong>Upload invitation certificate</strong><span>Choose the private image you received</span></label><div className="invitation-phrase"><label htmlFor="invitation-phrase">Three-word secret</label><div><input id="invitation-phrase" value={phrase} onChange={e=>setPhrase(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&phrase.trim())enter(phrase)}} placeholder="velvet penguin moonlight"/><button disabled={busy||!phrase.trim()} onClick={()=>enter(phrase)}>Enter</button></div></div><p role="status">{busy?'Checking…':message}</p></main>;
  return <><div className="access-bar"><span>Private invitation active</span><button onClick={showToken}>My token</button><button onClick={()=>{clearAccessToken();location.reload()}}>Lock</button></div>{children}<dialog ref={tokenDialog} className="token-dialog" onClick={e=>{if(e.target===tokenDialog.current)tokenDialog.current.close()}}><button className="token-dialog-close" aria-label="Close" onClick={()=>tokenDialog.current?.close()}>×</button><h2>My token</h2><p>Keep this private. Anyone with it can access your work.</p>{tokenImage&&<img src={tokenImage} alt="Your private invitation token"/>}<button onClick={download}>Download QR receipt</button></dialog></>
}
