import {useEffect,useRef,useState} from 'react';
import SecurityCheck from './SecurityCheck.jsx';
import StyleCatalog from './StyleCatalog.jsx';
import VectorEditor from './VectorEditor.jsx';
import {savedRequest,remember,createRequest,call,headers} from '../lib/name-logo-request.mjs';
export default function NameLogoGenerator({first,last,visible,onFirst,onLast,intro}){
 const [config,setConfig]=useState(null),[selected,setSelected]=useState([]),[request,setRequest]=useState(savedRequest),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[token,setToken]=useState(''),[message,setMessage]=useState(''),[assets,setAssets]=useState({}),[editing,setEditing]=useState(null);
 const [step,setStep]=useState('name');
 const active=useRef(null),cache=useRef({});
 useEffect(()=>{const c=new AbortController();fetch('/api/name-logo/catalog',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{setConfig(data);setSelected(['logo','initials','signature'].map(mode=>data.styles?.find(s=>s.mode===mode)).filter(Boolean).map(({mode,id})=>({mode,id})))}).catch(e=>{if(e.name!=='AbortError'){setConfig({enabled:false,styles:[]});setMessage('Could not connect. Refresh to try again.')}});return()=>{c.abort();active.current?.abort();Object.values(cache.current).forEach(a=>{URL.revokeObjectURL(a.png);if(a.svg)URL.revokeObjectURL(a.svg)})}},[]);
 async function load(current,design,signal){if(cache.current[design.id])return;const base='/api/name-logo/image?id='+design.id,r=await fetch(base,{headers:headers(current),signal});if(!r.ok)throw Error();const item={png:URL.createObjectURL(await r.blob())};if(design.output?.svg){const v=await fetch(base+'&format=svg',{headers:headers(current),signal});if(v.ok){item.source=await v.text();item.svg=URL.createObjectURL(new Blob([item.source],{type:'image/svg+xml'}))}}cache.current[design.id]=item;setAssets({...cache.current})}
 async function poll(current){active.current?.abort();const c=new AbortController();active.current=c;setBusy(true);try{const deadline=Date.now()+15*60*1000;while(Date.now()<deadline){const data=await call('status',current,{id:current.id},c.signal);if(!data.designs?.length)throw Error();setResult(data);for(const d of data.designs)if(d.status==='succeeded')await load(current,d,c.signal);const done=data.designs.filter(d=>!['queued','running'].includes(d.status)).length;setMessage(`${done} of ${data.designs.length} designs finished`);if(done===data.designs.length)return;await new Promise(r=>setTimeout(r,2500));c.signal.throwIfAborted()}setMessage('Still processing. Check progress again; your request is saved.')}catch(e){if(e.name!=='AbortError')setMessage('Connection interrupted. Your request is saved; check progress again.')}finally{if(active.current===c)setBusy(false)}}
 async function generate(){if(busy||request?.id||!token)return;let current;try{current=request||createRequest(first,last,selected);remember(current)}catch{setMessage('Allow browser storage so your request can be recovered.');return}setRequest(current);setBusy(true);const c=new AbortController();active.current=c;try{const selection=current.styles?{styles:current.styles}:{styleId:current.styleId};const data=await call('generate',current,{first:current.first,last:current.last,...selection,requestKey:current.requestKey,token},c.signal);if(!/^[a-f0-9]{64}$/.test(data.id))throw Error();const accepted={...current,id:data.id};remember(accepted);setRequest(accepted);await poll(accepted)}catch(e){if(e.name!=='AbortError')setMessage('Submission could not be confirmed. Recover the saved request; do not create another.')}finally{setBusy(false);setToken('')}}
 if(!visible)return null;
 return <>{!request&&step==='name'&&intro}<section className="live-logo-generator" aria-label="Create your designs">{!request&&<>{step==='name'?<><div className="shared-name"><label>Enter your first name<input id="first-name" value={first} maxLength={80} onChange={e=>onFirst(e.target.value)}/></label><label>Enter your last name<input id="last-name" value={last} maxLength={80} onChange={e=>onLast(e.target.value)}/></label></div><button className="identity-try-button" disabled={!first.trim()||!last.trim()} onClick={()=>setStep('styles')}>Continue →</button></>:<><div className="workspace-person"><strong>{first} {last}</strong><button onClick={()=>setStep('name')}>Edit name</button></div>{config&&<StyleCatalog first={first} last={last} styles={config.styles||[]} selected={selected} onChange={setSelected}/>}</>}</>}{!config?.enabled&&<p role="status">{config?'Generation is not available yet.':'Checking availabilityâ€¦'}</p>}{!request&&step==='styles'&&<>{config?.enabled&&<SecurityCheck config={config} action="name_logo" onToken={setToken} onError={setMessage}/>}<button className="identity-try-button" disabled={!config?.enabled||!selected.length||selected.some(s=>!s.id)||!first.trim()||!last.trim()||!token||busy} onClick={generate}>Generate</button></>}{busy&&<progress aria-label="Generating selected designs"/>}<p role="status">{message}</p>{request&&<header className="identity-results-heading"><h2>Designs for {request.first} {request.last}</h2><small>Request reference: {request.requestKey}</small></header>}{request&&!request.id&&!busy&&config?.enabled&&<><SecurityCheck config={config} action="name_logo" onToken={setToken} onError={setMessage}/><button disabled={!token} onClick={generate}>Recover saved request</button></>}{request?.id&&!busy&&<button onClick={()=>poll(request)}>Check progress</button>}<div className="design-collection">{result?.designs.map(d=><article className="design-card" key={d.id}><h3>{d.styleName}</h3>{assets[d.id]?<><img src={assets[d.id].png} alt={`${request.first} ${request.last} â€” ${d.styleName}`}/><div className="design-actions"><a href={assets[d.id].png} download={`${d.styleId}.png`}>Download PNG</a>{assets[d.id].svg?<><a href={assets[d.id].svg} download={`${d.styleId}.svg`}>Download SVG</a><button onClick={()=>setEditing(d.id)}>Edit design</button></>:<span>Vector unavailable; original PNG preserved.</span>}</div></>:<p>{d.status==='ambiguous'?'Result uncertain; this design will not be repeated automatically.':d.status}</p>}</article>)}</div>{result&&!busy&&result.designs.every(d=>!['queued','running','ambiguous'].includes(d.status))&&<button onClick={()=>{remember(null);setRequest(null);setResult(null);setEditing(null);setMessage('');Object.values(cache.current).forEach(a=>{URL.revokeObjectURL(a.png);if(a.svg)URL.revokeObjectURL(a.svg)});cache.current={};setAssets({})}}>Create another collection</button>}{editing&&<VectorEditor key={editing} source={assets[editing].source} onClose={()=>setEditing(null)}/>}</section></>
}
