import {useEffect,useRef,useState} from 'react';
import previews from '../lib/style-previews.json';
import InkPreview from './InkPreview.jsx';
const modes=[['logo','Name logo'],['initials','Initials'],['signature','Signature']];
export default function StyleCatalog({styles,selected,onChange}){
 const [active,setActive]=useState('logo'),[ink,setInk]=useState('#202720'),[open,setOpen]=useState(false);const dialog=useRef(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 const enabled=m=>selected.some(s=>s.mode===m),shown=styles.filter(s=>s.mode===active),chosen=selected.find(s=>s.mode===active)?.id,index=Math.max(0,shown.findIndex(s=>s.id===chosen)),current=shown[index];
 const defaults=m=>styles.find(s=>s.mode===m)?.id||'';
 function toggle(mode){if(enabled(mode)){const next=selected.filter(s=>s.mode!==mode);onChange(next);if(active===mode)setActive(next[0]?.mode||mode)}else{onChange([...selected,{mode,id:defaults(mode)}]);setActive(mode)}}
 function choose(id){onChange(selected.map(s=>s.mode===active?{mode:active,id}:s))}
 function artwork(style){return <InkPreview src={previews.find(p=>p.mode===style.mode&&p.id===style.id)?.src} color={ink} label={`${style.name} style example`}/>}
 return <section className="identity-workspace" aria-label="Choose outputs and styles"><h2>What would you like to create?</h2><p>Choose one, two, or all three.</p><div className="output-toggles">{modes.map(([mode,label])=><button key={mode} type="button" aria-pressed={enabled(mode)} onClick={()=>toggle(mode)}>{enabled(mode)?'✓ ':'＋ '}{label}</button>)}<button type="button" onClick={()=>onChange(modes.filter(([mode])=>defaults(mode)).map(([mode])=>selected.find(s=>s.mode===mode)||{mode,id:defaults(mode)}))}>All three</button></div><label className="ink-control">Preview ink color <input type="color" value={ink} onChange={e=>setInk(e.target.value)}/><span>{ink.toUpperCase()}</span></label><div className="workspace-split"><div className="workspace-rail">{modes.filter(([m])=>enabled(m)).map(([m,label])=><button key={m} type="button" aria-pressed={active===m} onClick={()=>setActive(m)}><strong>{label}</strong><small>{styles.find(s=>s.id===selected.find(x=>x.mode===m)?.id&&s.mode===m)?.name}</small></button>)}</div>{enabled(active)&&current?<div className="workspace-preview"><div className="workspace-style-heading"><div><small>Selected style</small><h3>{current.name}</h3></div><button type="button" onClick={()=>setOpen(true)}>Change style</button></div><div className="workspace-art">{artwork(current)}</div><div className="workspace-browse"><button type="button" aria-label="Previous style" onClick={()=>choose(shown[(index+shown.length-1)%shown.length].id)}>←</button><div className="gallery-dots">{shown.map(s=><button key={s.id} type="button" aria-label={s.name} aria-pressed={s.id===current.id} onClick={()=>choose(s.id)}/>)}</div><button type="button" aria-label="Next style" onClick={()=>choose(shown[(index+1)%shown.length].id)}>→</button></div><p className="workspace-reference">↑ Style example — your {active==='logo'?'name logo':active==='initials'?'initials':'signature'} will use your name.</p></div>:<p>Choose an output above.</p>}</div><dialog className="style-gallery-dialog" ref={dialog} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><div className="workspace-style-heading"><h2>Select {modes.find(m=>m[0]===active)[1].toLowerCase()} style</h2><button type="button" onClick={()=>setOpen(false)}>Close</button></div><p>{shown.length} styles · Choose one to update your preview.</p>{open&&<div className="style-gallery-items">{shown.map(s=><button key={s.id} type="button" aria-pressed={s.id===current?.id} onClick={()=>{choose(s.id);setOpen(false)}}>{artwork(s)}<strong>{s.name}</strong><small>{s.id===current?.id?'✓ Current style':'Select style'}</small></button>)}</div>}</dialog></section>
}
