import {useState} from 'react';
import previews from '../lib/style-previews.json';
const modes=[['logo','Magic Name'],['initials','Magic Initials'],['signature','Magic Signature']];
export default function StyleCatalog({styles,selected,onChange}){
 const [mode,setMode]=useState('logo');
 const shown=styles.filter(s=>s.mode===mode);const key=s=>s.mode+':'+s.id;
 const toggle=s=>onChange(selected.some(x=>key(x)===key(s))?selected.filter(x=>key(x)!==key(s)):[...selected,{mode:s.mode,id:s.id}]);
 return <section className="style-catalog" aria-label="Choose your designs"><div className="catalog-tabs" role="tablist">{modes.map(([id,label])=><button key={id} role="tab" aria-selected={mode===id} onClick={()=>setMode(id)}>{label}<small>{styles.filter(s=>s.mode===id).length}</small></button>)}</div><div className="catalog-summary"><span>Choose up to 20 styles per request.</span><button className="text-button" onClick={()=>onChange([...selected.filter(s=>s.mode!==mode),...shown.map(({mode,id})=>({mode,id}))].slice(0,20))}>Select all in this category</button><button className="text-button" onClick={()=>onChange(selected.filter(s=>s.mode!==mode))}>Clear</button></div><div className="style-grid">{shown.map(s=>{const checked=selected.some(x=>key(x)===key(s)),preview=previews.find(p=>key(p)===key(s));return <button type="button" className={'style-card'+(checked?' selected':'')} disabled={!checked&&selected.length>=20} aria-pressed={checked} onClick={()=>toggle(s)} key={key(s)}><div className="style-preview">{preview?<svg viewBox="0 0 480 320" role="img" aria-label={`${s.name} style reference`}><defs><filter id={`ink-${s.mode}-${s.id}`} colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -.2126 -.7152 -.0722 0 1" result="ink"/><feComposite in="ink" in2="SourceAlpha" operator="in" result="masked"/><feFlood floodColor="currentColor"/><feComposite in2="masked" operator="in"/></filter></defs><image href={preview.src} width="480" height="320" filter={`url(#ink-${s.mode}-${s.id})`}/></svg>:<span>{s.name}</span>}</div><div><strong>{s.name}</strong><span aria-hidden="true">{checked?'✓':'+'}</span></div><small>Style reference</small></button>})}</div><p className="selection-total">{selected.length} {selected.length===1?'design':'designs'} selected</p></section>
}

