import {useState} from 'react';
import previews from '../lib/style-previews.json';
const modes=[['logo','Name logo'],['initials','Initials'],['signature','Signature']];
export default function StyleCatalog({styles,selected,onChange}){
 const [active,setActive]=useState('logo');
 const enabled=mode=>selected.some(s=>s.mode===mode);
 const shown=styles.filter(s=>s.mode===active), chosen=selected.find(s=>s.mode===active)?.id;
 const index=Math.max(0,shown.findIndex(s=>s.id===chosen)), current=shown[index];
 const preview=previews.find(s=>s.mode===active&&s.id===current?.id);
 function toggle(mode){if(enabled(mode)){const next=selected.filter(s=>s.mode!==mode);onChange(next);if(active===mode)setActive(next[0]?.mode||mode)}else{onChange([...selected,{mode,id:''}]);setActive(mode)}}
 function choose(id){onChange(selected.map(s=>s.mode===active?{mode:active,id}:s))}
 return <section className="identity-workspace" aria-label="Choose outputs and styles"><h2>What would you like to create?</h2><p>Choose one, two, or all three. Select a style for each.</p><div className="output-toggles">{modes.map(([mode,label])=><button type="button" key={mode} aria-pressed={enabled(mode)} onClick={()=>toggle(mode)}>{enabled(mode)?'✓ ':'＋ '}{label}</button>)}<button type="button" onClick={()=>onChange(modes.map(([mode])=>selected.find(s=>s.mode===mode)||{mode,id:''}))}>All three</button></div><div className="workspace-split"><div className="workspace-rail" aria-label="Selected outputs">{modes.filter(([mode])=>enabled(mode)).map(([mode,label])=><button type="button" key={mode} aria-pressed={active===mode} onClick={()=>setActive(mode)}><strong>{label}</strong><small>{styles.find(s=>s.mode===mode&&s.id===selected.find(x=>x.mode===mode)?.id)?.name||'Choose a style'}</small></button>)}</div>{enabled(active)&&current?<div className="workspace-preview"><div className="workspace-style-heading"><label htmlFor="identity-style">{modes.find(m=>m[0]===active)[1]} style</label><span>{index+1} / {shown.length}</span></div><select id="identity-style" value={current.id} onChange={e=>choose(e.target.value)}>{shown.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="workspace-art">{preview&&<svg viewBox="0 0 480 320" role="img" aria-label={`${current.name} reference`}><defs><filter id="workspace-ink" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -.2126 -.7152 -.0722 0 1" result="ink"/><feComposite in="ink" in2="SourceAlpha" operator="in" result="masked"/><feFlood floodColor="currentColor"/><feComposite in2="masked" operator="in"/></filter></defs><image href={preview.src} width="480" height="320" filter="url(#workspace-ink)"/></svg>}</div><p className="workspace-reference">Style reference · Your design will use your name.</p><div className="workspace-browse"><button type="button" aria-label="Previous style" onClick={()=>choose(shown[(index+shown.length-1)%shown.length].id)}>←</button><button type="button" onClick={()=>choose(current.id)}>{chosen===current.id?'✓ Selected':'Select this style'}</button><button type="button" aria-label="Next style" onClick={()=>choose(shown[(index+1)%shown.length].id)}>→</button></div></div>:<p>Select an output to choose its style.</p>}</div><p>{selected.filter(s=>s.id).length} of {selected.length} styles selected</p></section>
}
