import {useState,useRef} from 'react';
export default function VectorEditor({source,onClose}){
 const [model,setModel]=useState(()=>{const doc=new DOMParser().parseFromString(source,'image/svg+xml'),root=doc.documentElement;if(root.localName!=='svg'||doc.querySelector('parsererror'))throw Error('Invalid SVG');return {viewBox:root.getAttribute('viewBox'),paths:[...root.querySelectorAll('path')].map(p=>({d:p.getAttribute('d'),base:p.getAttribute('transform')||'',x:0,y:0,color:'#000000',width:0}))}});
 const [handles,setHandles]=useState(false);
 const tokens=d=>d.match(/[MLCZmlcz]|[-+]?(?:\d*\.)?\d+(?:[eE][-+]?\d+)?/g)||[];
 const [selected,setSelected]=useState(0),[history,setHistory]=useState([]),[future,setFuture]=useState([]);const drag=useRef(null);
 function commit(next){setHistory(h=>[...h.slice(-49),model]);setFuture([]);setModel(next)}
 function edit(fields){commit({...model,paths:model.paths.map((p,i)=>i===selected?{...p,...fields}:p)})}
 function save(){const ns='http://www.w3.org/2000/svg',root=document.createElementNS(ns,'svg');root.setAttribute('xmlns',ns);root.setAttribute('viewBox',model.viewBox);for(const p of model.paths){const n=document.createElementNS(ns,'path');n.setAttribute('d',p.d);n.setAttribute('transform',`translate(${p.x} ${p.y}) ${p.base}`);n.setAttribute('fill',p.color);n.setAttribute('fill-rule','evenodd');n.setAttribute('stroke',p.color);n.setAttribute('stroke-width',p.width);root.appendChild(n)}const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(root)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='edited-design.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function position(e){const svg=e.currentTarget.ownerSVGElement||e.currentTarget;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())}
 return <section className="vector-editor" aria-label="SVG editor"><h3>Edit your design</h3><p>Select an outline and drag it. Your original stays unchanged.</p><div className="editor-tools"><button disabled={!history.length} onClick={()=>{setFuture(f=>[model,...f]);setModel(history.at(-1));setHistory(h=>h.slice(0,-1))}}>Undo</button><button disabled={!future.length} onClick={()=>{setHistory(h=>[...h,model]);setModel(future[0]);setFuture(f=>f.slice(1))}}>Redo</button><label><input type="checkbox" checked={handles} onChange={e=>setHandles(e.target.checked)}/>Curve points</label><label>Outline<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{model.paths.map((_,i)=><option key={i} value={i}>{i+1}</option>)}</select></label><label>Ink<input type="color" value={model.paths[selected]?.color||'#000000'} onChange={e=>edit({color:e.target.value})}/></label><label>Weight<input type="range" min="0" max="12" step=".5" value={model.paths[selected]?.width||0} onChange={e=>edit({width:Number(e.target.value)})}/></label></div><svg viewBox={model.viewBox} aria-label="Editable vector artwork" onPointerMove={e=>{if(!drag.current)return;const p=position(e),d=drag.current;if(d.point!==undefined){const path=d.model.paths[d.index],parts=tokens(path.d);parts[d.point]=String(Number(parts[d.point])+p.x-d.start.x);parts[d.point+1]=String(Number(parts[d.point+1])+p.y-d.start.y);setModel({...d.model,paths:d.model.paths.map((shape,i)=>i===d.index?{...shape,d:parts.join(' ')}:shape)});return;}setModel({...d.model,paths:d.model.paths.map((shape,i)=>i===d.index?{...shape,x:shape.x+p.x-d.start.x,y:shape.y+p.y-d.start.y}:shape)})}} onPointerUp={()=>{if(drag.current){setHistory(h=>[...h.slice(-49),drag.current.model]);setFuture([]);drag.current=null}}}>{model.paths.map((p,i)=><path key={i} d={p.d} transform={`translate(${p.x} ${p.y}) ${p.base}`} fill={p.color} fillRule="evenodd" stroke={p.color} strokeWidth={p.width} style={{cursor:'move',opacity:selected===i?.8:1}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setSelected(i);drag.current={index:i,start:position(e),model}}}/>) }{handles&&model.paths[selected]&&tokens(model.paths[selected].d).map((value,i,parts)=>{if(!Number.isFinite(Number(value))||!Number.isFinite(Number(parts[i+1])))return null;let start=i;while(start>0&&Number.isFinite(Number(parts[start-1])))start--;if((i-start)%2)return null;const shape=model.paths[selected];return <circle key={i} cx={Number(value)} cy={Number(parts[i+1])} r="4" fill="white" stroke="#1976d2" strokeWidth="1.5" transform={`translate(${shape.x} ${shape.y}) ${shape.base}`} onPointerDown={e=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);drag.current={index:selected,point:i,start:position(e),model}}}/>})}</svg><div className="editor-tools"><button onClick={save}>Download edited SVG</button><button onClick={onClose}>Done</button></div></section>
}

