'use client';
import genres from './genres.json';
import FrameCarousel from './frame-carousel';
import models from './guide.json';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '../components/ui/table';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '../components/ui/accordion';
const columns=[['seedance25','Seedance 2.5'],['veo','Veo 3.1'],['kling3','Kling 3.0'],['gen45','Gen-4.5'],['h3','H3'],['wan27','Wan 2.7'],['vidu','Vidu Q3'],['ray314','Luma Ray'],['pixverse','PixVerse C1']];
const bucket=(id:string)=>id==='ray32'?'ray314':id;
const modelName=(id:string)=>models.find(m=>m.id===id)?.name||id;
const link=(id:string)=><a href={'#'+id}>{modelName(id)}</a>;
const lighting=[
['Bioluminescent forests / glowing creatures','Veo 3.1; Gen-4.5','Start from an approved still. Ask for localized emission, soft spill on nearby surfaces and slow movement.','Emissive anatomy can drift. Bloom should not erase the subject. These are test candidates, not proven winners.'],
['Neon streets / wet reflections','Ray3.14 HDR generation; Gen-4.5','Use Ray HDR generation where available for highlight latitude, or Gen-4.5 for camera-led SDR shots.','Ray3.14 HDR/EXR is documented at 540p/720p generation, not Modify. Neon readability and reflection consistency need review.'],
['Fire, sunsets & high-contrast light','Ray HDR workflows; LTX-2.5','If finishing in HDR, choose a supported high-bit-depth output and manage color through export.','A bright-looking SDR frame is not HDR. Confirm the specific model, mode and output format.'],
['Soft daylight / realistic fur & skin','Veo 3.1; Gen-4.5','Use a natural-light reference, restrained contrast and one simple action.','Attractive texture in one frame does not prove correct animal gait, facial motion or stable lighting.'],
['Pastel animation / consistent art palettes','Vidu Q3; Seedance 2.5','Use a style sheet with a small set of colors, consistent materials and controlled references.','Exact colors can shift through generation and export; grade shots together afterward.']
];
export default function GenreMatrix({standalone=false}:{standalone?:boolean}){
const details=genres.map((g,i)=>{const content=<div className="genre-detail"><FrameCarousel genre={g.id} name={g.name} standalone={standalone}/><p><strong>Start here:</strong> {link(g.first)}. <strong>Also test:</strong> {g.alternatives.map((id,j)=><span key={id}>{j?' · ':''}{link(id)}</span>)}</p><div className="genre-guidance"><div><h4>Why this shortlist</h4><p>{g.why}</p></div><div><h4>How to make it</h4><p>{g.workflow}</p></div><div><h4>What can go wrong</h4><p>{g.risk}</p></div></div><p className="genre-evidence"><strong>Popularity evidence:</strong> {g.popularity}. This is not a current view-count ranking.</p><p className="sources">{g.sources.map((s,j)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{j?' · ':''}{s.label} ↗</a>)}</p></div>;return standalone?<details id={'genre-'+g.id} key={g.id}><summary>{String(i+1).padStart(2,'0')} / {g.name}</summary>{content}</details>:<AccordionItem id={'genre-'+g.id} value={g.id} key={g.id}><AccordionTrigger>{String(i+1).padStart(2,'0')} / {g.name}</AccordionTrigger><AccordionContent>{content}</AccordionContent></AccordionItem>});
return <section id="genre-matrix" className="section"><p className="eyebrow">THE SHORT-FORM PLAYBOOK / 20 GENRES & FORMATS</p><h2>What do you want to make?</h2><p className="matrix-intro">Pick the format first. Use this matrix to choose a starting model, then open the workflow notes for techniques, limitations and sources.</p><div className="notice"><strong>How we chose these:</strong> A researched selection of established short-video formats, platform-reported trends and the specific niches you asked about. It is not the “20 most popular” by measured views. Model fit is an editorial inference from documented capabilities and examples, not a controlled genre benchmark. Checked September 8, 2026.</div><div className="matrix-legend"><span className="fit first">★ Start here</span><span className="fit alternative">● Also test</span><span className="fit none">— Not shortlisted</span><p>A dash means no recommendation here, not that the model cannot do it. Colors retain their meaning across appearance themes.</p></div><p className="small">Scroll the table sideways on smaller screens. “Luma Ray” includes Ray3.14 generation and Ray3.2 Modify; the workflow below names the exact choice.</p><div className="genre-table" role="region" aria-label="Short-video genre model-fit matrix" tabIndex={0}><Table><TableHeader><TableRow><TableHead>Genre / format</TableHead>{columns.map(([id,n])=><TableHead key={id}><a href={'#'+id}>{n}</a></TableHead>)}<TableHead>Specialist options</TableHead></TableRow></TableHeader><TableBody>{genres.map(g=><TableRow key={g.id}><TableCell><a href={'#genre-'+g.id}>{g.name}<small>Workflow & evidence ↓</small></a></TableCell>{columns.map(([id])=>{const value=bucket(g.first)===id?'first':g.alternatives.some(x=>bucket(x)===id)?'alternative':'none';return <TableCell key={id}><span className={'fit '+value} aria-label={value==='first'?'Start here':value==='alternative'?'Also test':'Not shortlisted'}>{value==='first'?'★':value==='alternative'?'●':'—'}</span></TableCell>})}<TableCell>{[g.first,...g.alternatives].filter(id=>!columns.some(([c])=>c===bucket(id))).map(id=><div key={id}>{id===g.first?'★ ':'● '}{link(id)}</div>)}</TableCell></TableRow>)}</TableBody></Table></div>
<div className="genre-workflows model-help"><h3>Open a genre for the practical playbook</h3>{standalone?details:<Accordion>{details}</Accordion>}</div>
<div id="lighting-fit" className="lighting-guide"><p className="eyebrow">COLOR, LIGHT & LUMINESCENCE</p><h2>Glow is a look. HDR is an output capability.</h2><p className="matrix-intro">For luminous still photos, compare image models first. For animated glow, also judge flicker, reflections, motion and consistency. The site’s theme colors have no relationship to a model’s color quality.</p><Table><TableHeader><TableRow>{['Look','Starting shortlist','Direction','Watch out for'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{lighting.map(r=><TableRow key={r[0]}>{r.map(c=><TableCell key={c}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>
<div className="still-guidance"><h3>If you mean still photographs</h3><p><strong>FLUX.2</strong> is a practical candidate for photographic lighting and color-controlled product images; <strong>Midjourney with Style Reference</strong> is a candidate for a consistent luminous or fantasy aesthetic. Neither is established here as the universal “best luminescence” model. Create the still, approve it, then animate it with a supported image-to-video model.</p><p>For a useful comparison, use the same subject and lighting reference: a dark scene with one glowing object, visible nearby light spill and retained highlight detail. Compare color shifts, clipping, shadow detail and subject fidelity before adding motion.</p></div><p className="sources">Lighting & image sources: <a href="https://lumalabs.ai/learning-center/articles/luma-video-models-field-guide" target="_blank" rel="noreferrer">Luma mode/HDR guide ↗</a> · <a href="https://ltx.io/model/ltx-2-5" target="_blank" rel="noreferrer">LTX-2.5 formats ↗</a> · <a href="https://bfl.ai/models/flux-2" target="_blank" rel="noreferrer">FLUX.2 image capabilities ↗</a> · <a href="https://docs.midjourney.com/hc/en-us/articles/32180011136653-Style-Reference" target="_blank" rel="noreferrer">Midjourney Style Reference ↗</a></p></div></section>
}

