'use client';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '../components/ui/accordion';
type Model={id:string;name:string;kind:string;specs:string;best:string;sources:{url:string}[]};
const specific:Record<string,string[]>={
seedance25:['Gather consistent character, location and style references; add audio or movement references when needed.','Describe the sequence in timed beats and keep each action clear. Generate a short test before extending the story.','Review each cut for identity drift and use targeted edits for the part that failed.'],
veo:['Choose text-to-video for a new scene or image-to-video for an approved opening frame.','Write subject, action, camera and environment; describe dialogue and ambient sound separately.','Start with one short shot, check sound timing, then use the available reference or extension tools.'],
kling3:['Choose standard 3.0 or Omni according to the reference workflow you need.','Supply character references and describe each shot, action and spoken line.','Check continuity between shots and regenerate difficult interactions separately.'],
gen45:['Choose text or image generation; use an approved image when the composition must be anchored.','Describe one main action and a clear camera move. Set duration and frame rate for the edit.','Review the 720p output at full size, then finish resolution and audio in your production workflow.'],
h3:['Choose H3 for mixed references and editing, or H3 Max for its documented text/image workflow.','Set a supported duration and resolution for that exact variant, then describe movement and sound.','Test a short clip first. Do not transfer H3 settings to Max without checking its endpoint.'],
ray32:['Upload the source footage that establishes the motion and duration.','Place keyframes at important visual changes and describe the transformation between them.','Review transitions and export the format your finishing application needs.'],
sora:['Check whether the retiring API is still available in your account.','For existing projects only, choose a supported duration and output option and complete needed renders.','Export your work and migrate the integration before the announced API shutdown.']
};
export default function ModelHelp({model:m,standalone=false}:{model:Model;standalone?:boolean}){
const steps=specific[m.id]||(m.kind==='Editing'?['Start with footage that already has the timing, movement and composition you want.','Describe the intended changes and supply supported reference frames or keyframes.','Review the entire clip for unintended changes, then export into your editing workflow.']:m.kind==='Performance'?['Prepare a clear driving performance and a compatible character image or video.','Keep the face and relevant body movement visible; select the supported motion-transfer mode.','Check expressions, mouth timing and body motion before assembling the finished scene.']:m.kind==='Avatar'?['Choose or create a suitable presenter or character using the supported image/video input.','Supply a script or voice recording, then review pronunciation and performance settings.','Generate a short test before a long delivery; revise pacing and expression where needed.']:m.kind==='Open weights'?['Read the model card for licensing, GPU memory and installation requirements.','Load the exact checkpoint and a supported pipeline; begin with a small resolution and short test.','Tune supported settings gradually and record your configuration before scaling production.']:['Choose the exact model and a supported text, image or reference mode.','Describe the subject, action, camera and visual style. Start with one short, uncomplicated shot.','Review motion and consistency, change one instruction at a time, then finish sound and editing.']);
const params:[string,string][]=[
['Model / variant','The exact engine determines available controls. Fast, Turbo, Pro and Max are not interchangeable settings.'],
['Input / reference mode','Text creates a scene from a description. An image anchors appearance or the opening frame. Video, audio and additional references guide a supported workflow; not every model accepts all of them.'],
['Prompt','Describe what happens, how the camera moves and what should remain consistent. A long list of competing instructions can weaken the result.'],
['Duration','Clip length in seconds. Start short to test movement; longer clips create more opportunities for continuity errors. The limits shown above belong to the documented workflow.'],
['Resolution','The pixel dimensions of the output. Higher resolution can cost more and does not fix motion. Upscaled output is different from native generation.']
];
if(/audio|sound|voice/i.test(m.specs)||m.kind==='Avatar')params.push(['Audio / speech','Where available, choose or provide the voice, dialogue, music or ambience. Listen for pronunciation, timing and unintended sounds; audio input is not always generated audio.']);
if(/reference|keyframe|frame|Modify/i.test(m.specs)||m.kind==='Editing')params.push(['Reference frames / keyframes','References guide identity or style; first/last frames constrain endpoints; keyframes anchor moments within a sequence. Use only the controls offered by the selected mode.']);
if(m.kind==='Open weights')params.push(['Seed, steps & guidance','When your pipeline exposes them, seed sets the random starting state, steps control the sampling process, and guidance adjusts prompt influence. More steps or guidance are not automatically better; use the model card’s defaults.']);
if(m.id==='gen45')params.push(['Frame rate','Frames per second: the documented web workflow offers 24 or 25 fps. Choose the rate matching your timeline; this is separate from image resolution.']);
const contents=[<div key="steps"><p className="help-intro">Suggested workflow for {m.name}</p><ol>{steps.map(s=><li key={s}>{s}</li>)}</ol><p className="help-example"><strong>Try it for:</strong> {m.best}</p></div>,<div key="params"><p className="help-intro">Documented capability summary: {m.specs}. These explanations cover common controls; only use those exposed by your selected app or endpoint.</p><dl className="parameter-list">{params.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a href={m.sources[0].url} target="_blank" rel="noreferrer">Check exact controls and limits ↗</a></div>];
const labels=['How to use this model','Parameters explained'];
return <div className="model-help">{standalone?labels.map((l,i)=><details key={l}><summary>{l}</summary>{contents[i]}</details>):<Accordion>{labels.map((l,i)=><AccordionItem key={l} value={l}><AccordionTrigger>{l}</AccordionTrigger><AccordionContent>{contents[i]}</AccordionContent></AccordionItem>)}</Accordion>}</div>
}
