import data from './guide.json';
import themes from './themes.json';
import ThemeBehavior from './theme-behavior';
import ModelHelp from './model-help';
const leading=['seedance25','veo','kling3','gen45','h3','wan3'];
const guide=[...data].sort((a,b)=>{const rank=(m:typeof a)=>leading.includes(m.id)?leading.indexOf(m.id):/Legacy|Earlier|Sunsetting/.test(m.status)?100:20;return rank(a)-rank(b)});
import {Fragment} from 'react';
import media from './assets.json';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '../components/ui/table';
const choices=[
['A cinematic scene with sound','Seedance 2.5 · Veo 3.1 · Kling 3.0','Compare the same short script, including lip sync and environmental sound.'],
['Reference-heavy storytelling','Seedance 2.5 · H3 · Wan 3.0','Supply a consistent character sheet and inspect identity after each cut.'],
['A precisely art-directed shot','Gen-4.5 · Ray3.14 · Marey','Start with one clear action and a simple camera path.'],
['Change footage you already have','Ray3.2 Modify · Aleph 2.0 · Gemini Omni','Check that the edit preserves everything you intended to keep.'],
['Stylized social content','Pika · PixVerse · Midjourney Video','Choose the look first; compare motion and distortion at the end.'],
['Custom or self-hosted production','LTX-2.5 · Wan 2.2 · HunyuanVideo 1.5','Budget for GPUs, engineering, model licensing and finishing.'],
['Training or talking presenters','HeyGen · Synthesia · Hedra','Compare voice, pronunciation and expression on your real script.'],
['Transfer a recorded performance','Act-Two · Kling Motion Control','Use a clean driving clip with visible face and relevant body movement.']
];
const checkout='https://l3v-ai-cinema.lemonsqueezy.com/checkout/buy/c9e13261-739f-4c7c-a931-0cc1b94c1381';
function DirectorNote({final=false}:{final?:boolean}){return <aside className={'promo '+(final?'final-promo':'')} aria-label="Director Plus promotion"><div><p className="eyebrow">FROM L3V / DIRECTOR+</p><h2>{final?<>You have the model.<br/><em>Now direct the scene.</em></>:'A good model needs good direction.'}</h2><p>Explore camera, movement, lighting, visual prompts and audio direction in five creative studios. Build your shot with Director+.</p></div><div className="promo-actions"><a className="button gold" href={checkout} target="_blank" rel="noreferrer">Get Director+ <span>↗</span></a><a href="https://director.l3v.ai/" target="_blank" rel="noreferrer">Explore the five studios</a></div></aside>}
export default function Home({standalone=false}:{standalone?:boolean}={}){return <main><ThemeBehavior/>
<header><a className="brand" href="https://director.l3v.ai/"><img src="/l3v-mark.png" alt="L3V"/><span><strong>AI Video Modelpedia</strong><small>THE CRAFT OF AI FILMMAKING</small></span></a><div className="header-links"><a href="#index">The model guide</a><a className="button ghost" href="https://director.l3v.ai/" target="_blank" rel="noreferrer">Discover Director+ ↗</a></div></header><details className="theme-picker"><summary><span className="theme-dot"/> Appearance <span className="current-theme" data-theme-name>Arctic Cyan</span><span className="theme-count">25 palettes</span></summary><div className="theme-panel"><div><h2>Set the mood.</h2><p>Choose a color for the entire library. Your choice stays on this device.</p></div><div className="swatch-grid" aria-label="Color palette">{themes.map(t=><button type="button" key={t.id} data-theme-choice={t.id} aria-pressed={t.id==='arctic'} aria-label={'Use '+t.name+' theme'}><span style={{background:t.accent}}/><span>{t.name}</span></button>)}</div></div></details>
<section className="intro"><div className="intro-copy"><p className="eyebrow">AI VIDEO MODELPEDIA / BY L3V</p><h1>Find your model.<br/><em>Make your vision.</em></h1><p>A free field guide to AI video. Find the strengths, the trade-offs, and the right model for the shot you have in mind.</p><div className="intro-actions"><a className="button gold" href="#index">Explore 36 profiles <span>↓</span></a><a href="#choose">Help me choose ↗</a></div></div><div className="reel"><div className="reel-top"><span>THE MOVING IMAGE</span><span>REFERENCE / 001</span></div><a className="reel-image" style={{display:'block'}} href="#veo"><img src={media.assets.find(a=>a.family==='Veo')!.url} alt="Official Veo family video showcase"/></a><div className="reel-bottom"><span>VEO / OFFICIAL FAMILY DEMO</span><span>EXPLORE THE MODEL ↗</span></div><p className="reel-note">Every model has a point of view.<small>Learn where it shines. Know where to take control.</small></p></div></section>
<div className="edition"><span><b>36</b> comparison profiles</span><span><b>5</b> creative categories</span><span>Updated <b>08 Sep 2026</b></span><span>Free to read. No sign-up.</span></div>
<nav aria-label="Contents"><a href="#choose">Start with your task</a><a href="#index">All profiles</a><a href="#demos">About the imagery</a><a href="#method">Scope & methodology</a><a href="/ai-video-model-guide.html" download>Download HTML ↓</a></nav>
<aside className="notice"><strong>A broad view of the market.</strong> Major model families and their meaningful variants, grounded in official sources. Preview, legacy and retiring options are labeled. Access and features can vary by provider, account and region. <a href="#method">Read our methodology ↗</a></aside>
<section id="index" className="section model-directory"><div className="directory-heading"><div><p className="eyebrow">THE MODEL COLLECTION</p><h2>Start with the leading contenders.</h2></div><p>Six prominent general-purpose choices first. An editorial shortlist—not a benchmark ranking.</p></div><div className="featured-models">{guide.slice(0,6).map((m,i)=>{const asset=media.assets.find(a=>a.family===m.family&&!/\.(mp4|webm)(#|\?|$)/i.test(a.url));return <a className="feature-model" href={'#'+m.id} key={m.id}><div className="feature-visual">{asset?<img src={asset.url} alt={m.family+' official family showcase'} loading="lazy"/>:<div className="model-monogram" aria-hidden="true">{m.family==='Wan'?'WAN':'H3'}</div>}<span className="feature-label">{asset?'Official family showcase':'Model profile'}</span><span className="feature-arrow">↗</span></div><div className="feature-body"><p className="eyebrow">{m.maker} / {m.kind}</p><h3>{m.name}</h3><p>{m.summary}</p><div className="feature-specs">{m.specs}</div><span className="read-profile">Explore strengths & use cases <span>→</span></span></div></a>})}</div><div className="directory-heading remainder"><div><p className="eyebrow">GO DEEPER</p><h2>Every workflow. More possibilities.</h2></div><p>Generation, editing, performance and open models, with earlier releases clearly identified.</p></div><div className="collection-grid">{guide.slice(6).map(m=><a href={'#'+m.id} className="collection-card" key={m.id}><div className="collection-top"><span>{m.kind}</span><span>↗</span></div><h3>{m.name}</h3><p>{m.summary}</p><div className="collection-bottom"><span>{m.maker}</span><span>{m.status}</span></div></a>)}</div></section>
<section id="choose" className="section"><p className="eyebrow">01 / QUICK SELECTION</p><h2>Start with the job, not a ranking.</h2><Table><TableHeader><TableRow><TableHead>Your task</TableHead><TableHead>A useful shortlist</TableHead><TableHead>What to check first</TableHead></TableRow></TableHeader><TableBody>{choices.map(r=><TableRow key={r[0]}>{r.map(c=><TableCell key={c}>{c}</TableCell>)}</TableRow>)}</TableBody></Table><p className="small">Shortlists are editorial starting points, not measured winners. No single model is best across every task.</p></section>
<section id="demos" className="notice"><strong>How to read the examples.</strong> Images below are official demo posters or explicitly labeled thumbnails—not newly generated substitutes. Where only a video is available, two paused samples are embedded; press play to inspect motion. Family demos may be older than the profile. Their captions preserve that distinction. Missing verified assets are linked to the official showcase rather than replaced with unrelated pictures. Media loads from its original host and needs internet access.</section>
<section id="models">{guide.map((m,i)=>{const assets=media.assets.filter(a=>a.family===m.family).slice(0,2);return <Fragment key={m.id}><article id={m.id}><div className="heading"><span className="number">{String(i+1).padStart(2,'0')}</span><div><p className="eyebrow">{m.maker} / {m.kind}</p><h2>{m.name}</h2><p>{m.summary}</p></div><span className={'status '+(m.status==='Sunsetting'?'warning':'')}>{m.status}</span></div><div className="facts">{m.specs}</div><div className="grid">{[['Strengths',m.strengths],['Weaknesses',m.weaknesses],['Best scenario',m.best],['Worst scenario',m.worst]].map(([h,p])=><div key={h}><h3>{h}</h3><p>{p}</p></div>)}</div>
{assets.length>0?<div className="gallery">{assets.map((a,j)=>{const video=/\.(mp4|webm)(#|\?|$)/i.test(a.url);return <figure key={a.url}>{video?<video controls muted playsInline preload="metadata" src={a.url.includes('#')?a.url:a.url+'#t=0.1'} aria-label={a.kind}/>:<a href={a.source} target="_blank" rel="noreferrer"><img src={a.url} alt={a.family+' official showcase sample '+(j+1)} loading="lazy"/></a>}<figcaption><strong>Sample {j+1} · {a.version}</strong><br/>{a.kind}. <a href={a.source} target="_blank" rel="noreferrer">View original showcase ↗</a></figcaption></figure>})}</div>:<p className="media-gap">Two attributable sample images were not verified for this profile. <a href={m.sources[0].url} target="_blank" rel="noreferrer">Open the official documentation / showcase ↗</a></p>}
{assets.length===1&&<p className="small">Only one attributable visual was verified for this family.</p>}
<ModelHelp model={m} standalone={standalone}/><p className="sources">Sources: {m.sources.map((s,j)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{j>0?' · ':''}{s.label} ↗</a>)}</p><a className="back" href="#index">↑ Directory</a></article>{(i===9||i===23)&&<DirectorNote/>}</Fragment>})}</section>
<DirectorNote final/>
<section className="section"><p className="eyebrow">03 / THE EDGES OF THE MARKET</p><h2>Other names you will encounter.</h2><p>Earlier Seedance 1.x, Kling 1.x/2.x, Veo 2, Runway Gen-3, original Ray3 and earlier Hailuo/PixVerse releases can still appear in provider menus. They make sense for compatible existing workflows or favorable pricing; they are weaker default choices when you need newer controls. Do not infer availability from an old launch announcement.</p><p>Real-time systems such as Vidu S1 and PixVerse R1 target interactive or continuously evolving experiences. Their strength is responsiveness; their poor fit is a locked, reproducible final edit. Check current access and export controls directly with the <a href="https://www.vidu.com/">Vidu</a> and <a href="https://pixverse.ai/en">PixVerse</a> providers.</p><p>Research projects, community fine-tunes, AnimateDiff-style pipelines and world simulators are a much larger ecosystem than this buying guide. Research access, downloadable weights and a production service are different things. Haiper's current offering was not verified, so it is not an active recommendation here.</p><p>Higgsfield, fal, Replicate, Freepik and similar services can expose multiple underlying models. A provider brand or editing feature is not automatically a distinct foundation model. Compare the exact model ID and version before buying or integrating.</p></section>
<footer id="method"><p className="eyebrow">04 / METHOD & LIMITS</p><h2>A field guide, not a leaderboard.</h2><p>Capabilities and availability were checked against linked official pages on September 8, 2026. Vendor claims are not independent validation. Strengths, weaknesses and scenario recommendations are practical editorial inferences from documented capabilities—not results from a controlled hands-on benchmark.</p><p>For a fair decision, run the same three shots on your shortlist: one simple camera move, one person interacting with an object, and one scene representative of your real work. Count usable clips rather than generations. Check identity, hands, contact, text, continuity, voice timing and final resolution at full size.</p><p>Resolution alone does not measure quality. Native output and upscaling differ. Open weights do not mean free compute or unrestricted licensing. Fast, Turbo, Pro and Max names do not have consistent meanings across vendors.</p><p>Demo images are curated promotional evidence, and some thumbnails may include editorial design. They do not prove motion quality, audio accuracy or typical success rates. Shared family samples are illustrations of that family only—not evidence that every listed variant generated them. Remote hosts can change or block assets.</p><p>No paid generations were purchased for this report. Exact pricing is omitted because plans, provider markups, resolution and retries change the true cost. Verify the selected endpoint before committing to production.</p><div className="footer-line"><span>L3V / AI Video Modelpedia · Free reference</span><a href="https://director.l3v.ai/">Director+ ↗</a><a href="#">Back to top ↑</a></div></footer></main>}

