import guide from './guide.json';
import media from './assets.json';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '../components/ui/table';
const choices=[
['A cinematic scene with sound','Seedance 2.5 · Veo 3.1 · Kling 3.0','Compare the same short script, including lip sync and environmental sound.'],
['Reference-heavy storytelling','Seedance 2.5 · H3 · Wan 3.0','Supply a consistent character sheet and inspect identity after each cut.'],
['A precisely art-directed shot','Gen-4.5 · Ray3.14 · Marey','Start with one clear action and a simple camera path.'],
['Change footage you already have','Ray3.2 Modify · Aleph 2.0 · Gemini Omni','Check that the edit preserves everything you intended to keep.'],
['Stylized social content','Pika · PixVerse · Midjourney Video','Choose the look first; compare motion and distortion at the end.'],
['Custom or self-hosted production','LTX-2.5 · Wan 2.2 · HunyuanVideo 1.5','Budget for GPUs, engineering, model licensing and finishing.'],
['Training or talking presenters','HeyGen · Synthesia · Hedra','Compare voice, pronunciation and expression on your real script.'],
['Transfer a recorded performance','Act-Two · Kling Motion Control','Use a clean driving clip with visible face and relevant body movement.']
];
export default function Home(){return <main>
<header><a href="#">FRAME / FIELD GUIDE</a><span>RESEARCHED 08 SEP 2026</span></header>
<section className="intro"><p className="eyebrow">THE AI VIDEO LANDSCAPE / 36 COMPARISON PROFILES</p><h1>Choose the model.<br/><em>Make the shot.</em></h1><p>Strengths, weaknesses and practical use cases across cinematic generation, editing, open weights and avatars—with traceable official demos.</p></section>
<nav aria-label="Contents"><a href="#choose">Start with your task</a><a href="#index">All profiles</a><a href="#demos">About the imagery</a><a href="#method">Scope & methodology</a><a href="/ai-video-model-guide.html" download>Download HTML ↓</a></nav>
<aside className="notice"><strong>Market-wide, not literally every checkpoint.</strong> This guide covers major families and materially different variants found in official sources. Availability means offered by a provider or downloadable—not necessarily enabled in your account, region or Echora. Preview, legacy and retiring options are labeled.</aside>
<section id="choose" className="section"><p className="eyebrow">01 / QUICK SELECTION</p><h2>Start with the job, not a ranking.</h2><Table><TableHeader><TableRow><TableHead>Your task</TableHead><TableHead>A useful shortlist</TableHead><TableHead>What to check first</TableHead></TableRow></TableHeader><TableBody>{choices.map(r=><TableRow key={r[0]}>{r.map(c=><TableCell key={c}>{c}</TableCell>)}</TableRow>)}</TableBody></Table><p className="small">Shortlists are editorial starting points, not measured winners. No single model is best across every task.</p></section>
<section id="index" className="section"><p className="eyebrow">02 / THE DIRECTORY</p><h2>Explore the models.</h2><div className="index">{['Cinematic','Editing','Performance','Open weights','Avatar'].map(k=><div key={k}><h3>{k}</h3>{guide.filter(m=>m.kind===k).map(m=><a href={'#'+m.id} key={m.id}>{m.name}<span>↗</span></a>)}</div>)}</div></section>
<section id="demos" className="notice"><strong>How to read the examples.</strong> Images below are official demo posters or explicitly labeled thumbnails—not newly generated substitutes. Where only a video is available, two paused samples are embedded; press play to inspect motion. Family demos may be older than the profile. Their captions preserve that distinction. Missing verified assets are linked to the official showcase rather than replaced with unrelated pictures. Media loads from its original host and needs internet access.</section>
<section id="models">{guide.map((m,i)=>{const assets=media.assets.filter(a=>a.family===m.family).slice(0,2);return <article key={m.id} id={m.id}><div className="heading"><span className="number">{String(i+1).padStart(2,'0')}</span><div><p className="eyebrow">{m.maker} / {m.kind}</p><h2>{m.name}</h2><p>{m.summary}</p></div><span className={'status '+(m.status==='Sunsetting'?'warning':'')}>{m.status}</span></div><div className="facts">{m.specs}</div><div className="grid">{[['Strengths',m.strengths],['Weaknesses',m.weaknesses],['Best scenario',m.best],['Worst scenario',m.worst]].map(([h,p])=><div key={h}><h3>{h}</h3><p>{p}</p></div>)}</div>
{assets.length>0?<div className="gallery">{assets.map((a,j)=>{const video=/\.(mp4|webm)(#|\?|$)/i.test(a.url);return <figure key={a.url}>{video?<video controls muted playsInline preload="metadata" src={a.url.includes('#')?a.url:a.url+'#t=0.1'} aria-label={a.kind}/>:<a href={a.source} target="_blank" rel="noreferrer"><img src={a.url} alt={a.family+' official showcase sample '+(j+1)} loading="lazy"/></a>}<figcaption><strong>Sample {j+1} · {a.version}</strong><br/>{a.kind}. <a href={a.source} target="_blank" rel="noreferrer">View original showcase ↗</a></figcaption></figure>})}</div>:<p className="media-gap">Two attributable sample images were not verified for this profile. <a href={m.sources[0].url} target="_blank" rel="noreferrer">Open the official documentation / showcase ↗</a></p>}
{assets.length===1&&<p className="small">Only one attributable visual was verified for this family.</p>}
<p className="sources">Sources: {m.sources.map((s,j)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{j>0?' · ':''}{s.label} ↗</a>)}</p><a className="back" href="#index">↑ Directory</a></article>})}</section>
<section className="section"><p className="eyebrow">03 / THE EDGES OF THE MARKET</p><h2>Other names you will encounter.</h2><p>Earlier Seedance 1.x, Kling 1.x/2.x, Veo 2, Runway Gen-3, original Ray3 and earlier Hailuo/PixVerse releases can still appear in provider menus. They make sense for compatible existing workflows or favorable pricing; they are weaker default choices when you need newer controls. Do not infer availability from an old launch announcement.</p><p>Real-time systems such as Vidu S1 and PixVerse R1 target interactive or continuously evolving experiences. Their strength is responsiveness; their poor fit is a locked, reproducible final edit. Check current access and export controls directly with the <a href="https://www.vidu.com/">Vidu</a> and <a href="https://pixverse.ai/en">PixVerse</a> providers.</p><p>Research projects, community fine-tunes, AnimateDiff-style pipelines and world simulators are a much larger ecosystem than this buying guide. Research access, downloadable weights and a production service are different things. Haiper's current offering was not verified, so it is not an active recommendation here.</p><p>Higgsfield, fal, Replicate, Freepik and similar services can expose multiple underlying models. A provider brand or editing feature is not automatically a distinct foundation model. Compare the exact model ID and version before buying or integrating.</p></section>
<footer id="method"><p className="eyebrow">04 / METHOD & LIMITS</p><h2>A field guide, not a leaderboard.</h2><p>Capabilities and availability were checked against linked official pages on September 8, 2026. Vendor claims are not independent validation. Strengths, weaknesses and scenario recommendations are practical editorial inferences from documented capabilities—not results from a controlled hands-on benchmark.</p><p>For a fair decision, run the same three shots on your shortlist: one simple camera move, one person interacting with an object, and one scene representative of your real work. Count usable clips rather than generations. Check identity, hands, contact, text, continuity, voice timing and final resolution at full size.</p><p>Resolution alone does not measure quality. Native output and upscaling differ. Open weights do not mean free compute or unrestricted licensing. Fast, Turbo, Pro and Max names do not have consistent meanings across vendors.</p><p>Demo images are curated promotional evidence, and some thumbnails may include editorial design. They do not prove motion quality, audio accuracy or typical success rates. Shared family samples are illustrations of that family only—not evidence that every listed variant generated them. Remote hosts can change or block assets.</p><p>No paid generations were purchased for this report. Exact pricing is omitted because plans, provider markups, resolution and retries change the true cost. Verify the selected endpoint before committing to production.</p><a href="#">Back to top ↑</a></footer></main>}

