export async function initializeAnalyzer(){
 const form=document.querySelector<HTMLFormElement>('#reference-form');if(!form)return;
 const status=document.querySelector<HTMLElement>('#reference-status')!;const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;
 const file=form.elements.namedItem('image') as HTMLInputElement;const url=form.elements.namedItem('video') as HTMLInputElement;
 file.addEventListener('change',()=>{if(file.files?.length)url.value=''});url.addEventListener('input',()=>{if(url.value)file.value=''});
 let token='',widget:string|undefined;const ts=()=> (window as any).turnstile;
 try{const config=await fetch('/api/analyzer/config').then(r=>r.json());if(!config.enabled||!config.sitekey){status.textContent='The analyzer is being connected. The free model guide is available below.';return}
 const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>{widget=ts().render('#reference-security',{sitekey:config.sitekey,action:'reference_analyze',theme:'auto',callback:(t:string)=>{token=t;button.disabled=false;status.textContent='Ready to analyze your reference.'},'expired-callback':()=>{token='';button.disabled=true},'error-callback':()=>{status.textContent='Security check could not load. Refresh to try again.'}})};document.head.append(script);
 }catch{status.textContent='The analyzer is unavailable. Please try again later.';return}
 const wait=(media:HTMLMediaElement,event:string)=>new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>finish(new Error('Video could not load. Try uploading a reference image.')),15000);const ok=()=>finish();const fail=()=>finish(new Error('This video cannot be accessed. Upload a reference image instead.'));function finish(e?:Error){clearTimeout(timeout);media.removeEventListener(event,ok);media.removeEventListener('error',fail);e?reject(e):resolve()}media.addEventListener(event,ok,{once:true});media.addEventListener('error',fail,{once:true})});
 async function imageData(){const f=file.files?.[0];if(!f)throw new Error('Choose an image or enter a video URL.');if(f.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))throw new Error('Choose a JPEG, PNG or WebP image up to 8 MB.');const bitmap=await createImageBitmap(f);try{const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d')!;context.fillStyle='white';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.8)}finally{bitmap.close()}}
 async function videoData(){const u=new URL(url.value);if(u.protocol!=='https:'||u.username||u.password||!/^.*\.(mp4|webm)$/i.test(u.pathname))throw new Error('Use a direct HTTPS MP4/WebM link, or upload an image from the video.');const video=document.createElement('video');video.crossOrigin='anonymous';video.muted=true;video.preload='metadata';try{const ready=wait(video,'loadedmetadata');video.src=u.href;await ready;if(!Number.isFinite(video.duration)||video.duration<=0||video.duration>60)throw new Error('Use a video up to 60 seconds, or upload an image.');const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=400;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#111';ctx.fillRect(0,0,1200,400);for(let i=0;i<3;i++){const sought=wait(video,'seeked');video.currentTime=video.duration*[.15,.5,.85][i];await sought;const scale=Math.min(400/video.videoWidth,380/video.videoHeight);ctx.drawImage(video,i*400+(400-video.videoWidth*scale)/2,0,video.videoWidth*scale,video.videoHeight*scale);ctx.fillStyle='white';ctx.font='14px Arial';ctx.fillText('Sample '+(i+1),i*400+10,395)}return canvas.toDataURL('image/jpeg',.8)}finally{video.removeAttribute('src');video.load()}}
 form.addEventListener('submit',async e=>{e.preventDefault();if(!token)return;button.disabled=true;const result=document.querySelector<HTMLElement>('#reference-result')!;result.hidden=true;status.textContent='Preparing your reference…';try{const kind=file.files?.length?'image':'video';const image=kind==='image'?await imageData():await videoData();const preview=document.querySelector('#reference-preview')!;const img=new Image();img.src=image;img.alt='Reference being analyzed';preview.replaceChildren(img);status.textContent='Analyzing the reference and matching models…';const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,image,sourceUrl:kind==='video'?url.value:undefined,token}),signal:AbortSignal.timeout(100000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed.');const r=data.report;result.replaceChildren();const add=(tag:string,text:string)=>{const el=document.createElement(tag);el.textContent=text;result.append(el)};add('h2','Your creation plan');add('p',r.summary);add('h3','Recommended models');for(const m of r.models){const a=document.createElement('a');a.href='#'+m.id;a.textContent=m.id+' ↗';result.append(a);add('p',m.reason)}for(const [key,title] of [['observations','What we can see'],['workflow','How to build it'],['limitations','Limitations']]){add('h3',title);for(const text of r[key])add('p',text)}add('h3','Suggested starting prompt');add('p',r.prompt);result.hidden=false;status.textContent='Analysis complete.'}catch(error){status.textContent=error instanceof Error?error.message:'Could not analyze this reference.'}finally{token='';if(widget!==undefined)ts().reset(widget)}});
}
