import QRCode from 'qrcode';import jsQR from 'jsqr';
const key='l3v-master-access-v1',pattern=/^[A-Za-z0-9_-]{43}$/;
export function accessToken(){if(typeof localStorage==='undefined')return null;const value=localStorage.getItem(key);return pattern.test(value||'')?value:null}
export function saveAccessToken(value){if(!pattern.test(value||''))throw Error('Invalid invitation');localStorage.setItem(key,value);return value}
export function clearAccessToken(){localStorage.removeItem(key)}
export function accessHeaders(headers={}){const token=accessToken();return token?{...headers,'X-L3V-Invitation':token}:headers}
export async function accessFetch(url,options={}){return fetch(url,{...options,headers:accessHeaders(options.headers)})}
export async function requestReceipt(requestId,token=accessToken()){if(!/^[a-f0-9]{32}$/.test(requestId))throw Error('Invitation required');if(!token&&typeof process!=='undefined'&&process.versions?.node)return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');if(!token)throw Error('Invitation required');const keyData=await crypto.subtle.importKey('raw',new TextEncoder().encode(token),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',keyData,new TextEncoder().encode('l3v-request-v1\0'+requestId));return Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,'0')).join('')}
export function receiptPayload(token=accessToken()){if(!token)throw Error('Invitation required');return JSON.stringify({type:'l3v-access',version:1,token})}
export async function receiptImage(token=accessToken()){return QRCode.toDataURL(receiptPayload(token),{errorCorrectionLevel:'H',margin:3,width:720,color:{dark:'#171712',light:'#faf9f3'}})}
export async function tokenFromImage(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);bitmap.close();const found=jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,{inversionAttempts:'attemptBoth'});if(!found)throw Error('No l3v access code was found in this image.');let payload;try{payload=JSON.parse(found.data)}catch{throw Error('This is not an l3v access certificate.');}if(payload?.type!=='l3v-access'||payload.version!==1||!pattern.test(payload.token||''))throw Error('This access certificate is invalid.');return payload.token}
