import QRCode from 'qrcode';import jsQR from 'jsqr';
const key='l3v-master-access-v1',certificateKey='l3v-master-certificate-v1',tokenPattern=/^[A-Za-z0-9_-]{43}$/,accountPattern=/^[a-f0-9]{64}$/;
function stored(){if(typeof localStorage==='undefined')return {};const value=localStorage.getItem(key);if(tokenPattern.test(value||''))return {credential:value};try{return JSON.parse(value)||{}}catch{return {}}}
export function accessToken(){const value=stored().credential;return typeof value==='string'&&value.length>=3&&value.length<=180?value:null}
export function accessAccountId(){const value=stored().accountId;return accountPattern.test(value||'')?value:null}
export function saveAccessToken(credential,accountId){if(typeof credential!=='string'||credential.trim().length<3||credential.trim().length>180||!accountPattern.test(accountId||''))throw Error('Invalid invitation');localStorage.setItem(key,JSON.stringify({credential:credential.trim(),accountId}));return credential}
export function clearAccessToken(){localStorage.removeItem(key);localStorage.removeItem(certificateKey)}
export function savedCertificateImage(){return typeof localStorage==='undefined'?null:localStorage.getItem(certificateKey)}
export function saveCertificateImage(file){if(!file||file.size>4500000)throw Error('Invitation image is too large to save.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Invitation image could not be saved.'));reader.onload=()=>{localStorage.setItem(certificateKey,reader.result);resolve(reader.result)};reader.readAsDataURL(file)})}
export function accessHeaders(headers={}){const token=accessToken();return token?{...headers,'X-L3V-Invitation':token}:headers}
export async function accessFetch(url,options={}){return fetch(url,{...options,headers:accessHeaders(options.headers)})}
export async function requestReceipt(requestId,accountId=accessAccountId()){if(!/^[a-f0-9]{32}$/.test(requestId))throw Error('Invitation required');if(!accountId&&typeof process!=='undefined'&&process.versions?.node)return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');if(!accountId)throw Error('Invitation required');const keyData=await crypto.subtle.importKey('raw',new TextEncoder().encode(accountId),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',keyData,new TextEncoder().encode('l3v-request-v1\0'+requestId));return Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,'0')).join('')}
export function receiptPayload(credential=accessToken()){if(!credential)throw Error('Invitation required');return JSON.stringify({type:'l3v-access',version:1,credential})}
export async function receiptImage(credential=accessToken()){return QRCode.toDataURL(receiptPayload(credential),{errorCorrectionLevel:'H',margin:3,width:720,color:{dark:'#171712',light:'#faf9f3'}})}
export async function tokenFromImage(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);bitmap.close();const found=jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,{inversionAttempts:'attemptBoth'});if(!found)throw Error('No l3v access code was found in this image.');let payload;try{payload=JSON.parse(found.data)}catch{throw Error('This is not an l3v access certificate.');}const credential=payload?.credential||payload?.token;if(payload?.type!=='l3v-access'||payload.version!==1||typeof credential!=='string'||credential.length<3||credential.length>180)throw Error('This access certificate is invalid.');return credential}
